// Exports ABIs from Foundry artifacts into packages/shared/src/abis/*.ts as `as const` arrays (typed for viem).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "../out");
const target = join(here, "../../shared/src/abis");
mkdirSync(target, { recursive: true });

const contracts = {
  TrestleEscrow: "TrestleEscrow.sol/TrestleEscrow.json",
  TrestleAuthenticity: "TrestleAuthenticity.sol/TrestleAuthenticity.json",
  TrestleReputation: "TrestleReputation.sol/TrestleReputation.json",
  TrestleLoyalty: "TrestleLoyalty.sol/TrestleLoyalty.json",
  TrestlePaymentRouter: "TrestlePaymentRouter.sol/TrestlePaymentRouter.json",
  TrestlePaymaster: "TrestlePaymaster.sol/TrestlePaymaster.json",
  AttestationRelayerAdapter: "AttestationRelayerAdapter.sol/AttestationRelayerAdapter.json",
  TestToken: "TestToken.sol/TestToken.json",
  EntryPoint: "EntryPoint.sol/EntryPoint.json",
  SimpleAccountFactory: "SimpleAccountFactory.sol/SimpleAccountFactory.json",
  SimpleAccount: "SimpleAccount.sol/SimpleAccount.json",
};

const index = [];
for (const [name, rel] of Object.entries(contracts)) {
  const { abi } = JSON.parse(readFileSync(join(out, rel), "utf8"));
  const constName = name.charAt(0).toLowerCase() + name.slice(1) + "Abi";
  writeFileSync(
    join(target, `${name}.ts`),
    `// AUTO-GENERATED by packages/contracts/script/export-abis.mjs — do not edit.\nexport const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  index.push(`export { ${constName} } from "./${name}";`);
}
writeFileSync(join(target, "index.ts"), index.join("\n") + "\n");
console.log(`exported ${index.length} ABIs to ${target}`);
